apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: eW91cl9hd3Nfa2V5X2lk
  AWS_SECRET_ACCESS_KEY: eW91cl9hd3Nfc2VjcmV0
  S3_BUCKET: eW91cl9hd3Nfc2VjcmV0 #bucket
  S3_ENPOINT: eW91cl9hd3Nfc2VjcmV0 #s3 endpoint